type ItemMenu = {
  id: string
  tags: string[]
  title: string
  subtitle: string
  value: string
  amount: number
  image: string
}

export const itemMenu: ItemMenu[] = [
  {
    id: '1',
    image: 'expresso-tradicional.png',
    title: 'Expresso Tradicional',
    subtitle: 'O tradicional café feito com água quente e grãos moídos',
    value: '9,90',
    amount: 1,
    tags: ['tradicional'],
  },
  {
    id: '2',
    image: 'expresso-americano.png',
    title: 'Expresso Americano',
    subtitle: 'Expresso diluído, menos intenso que o tradicional',
    value: '9,90',
    amount: 1,
    tags: ['tradicional'],
  },
  {
    id: '3',
    image: 'expresso-cremoso.png',
    title: 'Expresso Cremoso',
    subtitle: 'Café expresso tradicional com espuma cremosa',
    value: '9,90',
    amount: 1,
    tags: ['tradicional'],
  },
  {
    id: '4',
    image: 'expresso-gelado.png',
    title: 'Expresso Gelado',
    subtitle: 'Bebida preparada com café expresso e cubos de gelo',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'gelado'],
  },
  {
    id: '5',
    image: 'cafe-com-leite.png',
    title: 'Café com Leite',
    subtitle: 'Meio a meio de expresso tradicional com leite vaporizado',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '6',
    image: 'latte.png',
    title: 'Latte',
    subtitle: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '7',
    image: 'capuccino.png',
    title: 'Capuccino',
    subtitle: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '8',
    image: 'macchiato.png',
    title: 'Macchiato',
    subtitle: 'Café expresso misturado com um pouco de leite quente e espuma',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '9',
    image: 'mocaccino.png',
    title: 'Mocaccino',
    subtitle: 'Café expresso com calda de chocolate, pouco leite e espuma',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '10',
    image: 'chocolate-quente.png',
    title: 'Chocolate Quente',
    subtitle: 'Bebida feita com chocolate dissolvido no leite quente e café',
    value: '9,90',
    amount: 1,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '11',
    image: 'cubano.png',
    title: 'Cubano',
    subtitle: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    value: '9,90',
    amount: 1,
    tags: ['especial', 'alcoólico', 'gelado'],
  },
  {
    id: '12',
    image: 'havaiano.png',
    title: 'Havaiano',
    subtitle: 'Bebida adocicada preparada com café e leite de coco',
    value: '9,90',
    amount: 1,
    tags: ['especial'],
  },
  {
    id: '13',
    image: 'arabe.png',
    title: 'Árabe',
    subtitle: 'Bebida preparada com grãos de café árabe e especiarias',
    value: '9,90',
    amount: 1,
    tags: ['especial'],
  },
  {
    id: '14',
    image: 'irlandes.png',
    title: 'Irlandês',
    subtitle: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    value: '9,90',
    amount: 1,
    tags: ['especial', 'alcoólico'],
  },
]
